export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';
export const ERROR_DISMISS = 'ERROR_DISMISS';

// AUTH

export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILURE = 'CHECK_TOKEN_FAILURE';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAILURE = 'UPDATE_TOKEN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const RESTORE_PASSWORD = 'RESTORE_PASSWORD';
export const RESTORE_PASSWORD_SUCCESS = 'RESTORE_PASSWORD_SUCCESS';
export const RESTORE_PASSWORD_FAILURE = 'RESTORE_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ESIA_LINK = 'ESIA_LINK';
export const ESIA_LINK_SUCCESS = 'ESIA_LINK_SUCCESS';
export const ESIA_LINK_FAILURE = 'ESIA_LINK_FAILURE';

export const ESIA_AUTH = 'ESIA_AUTH';
export const ESIA_AUTH_SUCCESS = 'ESIA_AUTH_SUCCESS';
export const ESIA_AUTH_FAILURE = 'ESIA_AUTH_FAILURE';

// USER

export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const SELECT_PHONE = 'SELECT_PHONE';

export const MSISDNS_FETCH = 'MSISDNS_FETCH';
export const MSISDNS_FETCH_SUCCESS = 'MSISDNS_FETCH_SUCCESS';
export const MSISDNS_FETCH_FAILURE = 'MSISDNS_FETCH_FAILURE';

export const BALANCE_FETCH = 'BALANCE_FETCH';
export const BALANCE_FETCH_SUCCESS = 'BALANCE_FETCH_SUCCESS';
export const BALANCE_FETCH_FAILURE = 'BALANCE_FETCH_FAILURE';

// APP

export const READ_STATE = 'READ_STATE';
export const RESET_STATE = 'RESET_STATE';

export const OFFER_TOGGLE = 'OFFER_TOGGLE';
export const POLICY_TOGGLE = 'POLICY_TOGGLE';
export const DO_NOT_PERSIST_TOGGLE = 'DO_NOT_PERSIST_TOGGLE';

export const BANNERS_SEEN = 'BANNERS_SEEN';

export const BIOMETRY_SET_TYPES = 'BIOMETRY_SET_TYPES';
export const BIOMETRY_SET_SAVED = 'BIOMETRY_SET_SAVED';

export const SEND_LEAD = 'SEND_LEAD';
export const SEND_LEAD_SUCCESS = 'SEND_LEAD_SUCCESS';
export const SEND_LEAD_FAILURE = 'SEND_LEAD_FAILURE';
